//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiTankGame2.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntiTankGame2.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort this game.
        /// </summary>
        internal static string AbortThisGame {
            get {
                return ResourceManager.GetString("AbortThisGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to abort this simulation?.
        /// </summary>
        internal static string AreYouWantToAbort {
            get {
                return ResourceManager.GetString("AreYouWantToAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to exit?.
        /// </summary>
        internal static string AreYouWantToExit {
            get {
                return ResourceManager.GetString("AreYouWantToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough video memory. {0} {0} Featured minimum graphics setting. Please restart the application {0} {0} If the message continues appearing, your system does not meet the minimum requirements.
        /// </summary>
        internal static string ErrorOutOfVideoMemory {
            get {
                return ResourceManager.GetString("ErrorOutOfVideoMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntiTankGame.
        /// </summary>
        internal static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsMenu {
            get {
                return ResourceManager.GetString("OptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused Menu.
        /// </summary>
        internal static string PauseMenu {
            get {
                return ResourceManager.GetString("PauseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Training.
        /// </summary>
        internal static string PlayGame {
            get {
                return ResourceManager.GetString("PlayGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuitGame.
        /// </summary>
        internal static string QuitGame {
            get {
                return ResourceManager.GetString("QuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Game.
        /// </summary>
        internal static string ResumeGame {
            get {
                return ResourceManager.GetString("ResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This adapter does not support Shader Model 2.0..
        /// </summary>
        internal static string SystemRequirements {
            get {
                return ResourceManager.GetString("SystemRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}A button, Space, Enter = ok{0}B button, Esc = cancel.
        /// </summary>
        internal static string UsageText {
            get {
                return ResourceManager.GetString("UsageText", resourceCulture);
            }
        }
    }
}
